/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AudioTrack } from "./AudioTrack";
import { AudioTrackCountArgs } from "./AudioTrackCountArgs";
import { AudioTrackFindManyArgs } from "./AudioTrackFindManyArgs";
import { AudioTrackFindUniqueArgs } from "./AudioTrackFindUniqueArgs";
import { DeleteAudioTrackArgs } from "./DeleteAudioTrackArgs";
import { AudioTrackService } from "../audioTrack.service";
@graphql.Resolver(() => AudioTrack)
export class AudioTrackResolverBase {
  constructor(protected readonly service: AudioTrackService) {}

  async _audioTracksMeta(
    @graphql.Args() args: AudioTrackCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AudioTrack])
  async audioTracks(
    @graphql.Args() args: AudioTrackFindManyArgs
  ): Promise<AudioTrack[]> {
    return this.service.audioTracks(args);
  }

  @graphql.Query(() => AudioTrack, { nullable: true })
  async audioTrack(
    @graphql.Args() args: AudioTrackFindUniqueArgs
  ): Promise<AudioTrack | null> {
    const result = await this.service.audioTrack(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AudioTrack)
  async deleteAudioTrack(
    @graphql.Args() args: DeleteAudioTrackArgs
  ): Promise<AudioTrack | null> {
    try {
      return await this.service.deleteAudioTrack(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
